In [1]:
import numpy as np

In [15]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [16]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [4]:
print(x+y)

[5 7 9]


In [5]:
type(x)

numpy.ndarray

In [6]:
type(y)

numpy.ndarray

In [8]:
# 연속된 정수 벡터의 생성
print(np.arange(10))    # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(np.arange(5, 10)) # [5,  6, 7, 8, 9]

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]


In [22]:
# ndarray 형의 주의점
# ndarray는 값을 복사하지 않고 주소를 전달
a = np.array([1, 2])
print(a)
b = a
print(b)

b[0] = 10 # Call By Reference
print(b)
print(a)

b = a.copy() # 벡터 값 그대로 복사 (주소값 참조 X)
b[0] = 11
print(b)
print(a)

[1 2]
[1 2]
[10  2]
[10  2]
[11  2]
[10  2]
